#!/bin/bash

###########################################################
#                                                         #
#   This is a buildscript for OOC - Ch03                 #
#   Change the value of $FILE and $COMPILER as needed     #
#                                                         #
#     usage: ./build or ./build clean                     #
#                                                         #
###########################################################

echo " "
echo "------------------Build start: Ch04------------"
echo " "

FILE1='Point'
FILE2='Circle'
FILE3='new'

COMPILER='gcc'
# COMPLIER='clang'

echo "  Compiling Files: $FILE1, $FILE2, $FILE3"
echo "  Using Compiler: $COMPILER"

MAIN='main'
CFLAGS_COMPILE=' -c -Wall -std=c99 -O0'
CFLAGS_BUILD=' -Wall -std=c99 -O0'
OUT='-o bin/'
SRC='src/'
BIN='bin/'
MOVE_TO_BIN='mv *.o bin/'


        if [ "$1" == "clean" ]; then
                echo "  Cleaning Only: bin"
                rm -f bin/*.o bin/*.exe

                if [ "$2" == "only" ]; then
                        echo " "
                        echo "-----------------Clean complete----------------"
                        exit 0; fi
        fi


echo " "
echo "  Begin compliation"

        $COMPILER $CFLAGS_COMPILE $SRC$FILE1\.c $SRC$FILE2\.c $SRC$FILE3\.c

echo "  Relocate files to bin"
        $MOVE_TO_BIN

        $COMPILER $CFLAGS_BUILD $OUT$MAIN $BIN$FILE1\.o $BIN$FILE2\.o $BIN$FILE3\.o $SRC$MAIN\.c

echo "  Compilation complete"
echo " "
echo "-----------------Build complete----------------"
echo " "
echo " "

exit 0
