#!/bin/bash

###########################################################
#                                                         #
#   This is a buildscript for OOC / Scratch               #
#   Change the value of $FILE and $COMPILER as needed     #
#                                                         #
#       usage: ./build or ./build clean                   #
#                                                         #
#       if there are problems - dos2unix / unix2dos       #
#                                                         #
###########################################################

echo " "
echo "------------------Build start: Scratch---------"
echo " "

FILE1='vectors'

# COMPILER='gcc'
COMPILER='clang'

MAIN='main'
CFLAGS_COMPILE=' -c -Wall -std=c99 -O0'
CFLAGS_BUILD=' -Wall -std=c99 -O0'
OUT='-o bin/'
SRC='src/'
BIN='bin/'
MOVE_TO_BIN='mv *.o bin/'

echo "  Compiling File: $FILE1"
echo "  Using Compiler: $COMPILER"

        if [ "$1" == "clean" ]; then
                echo "  Cleaning Only: bin"
                rm -f bin/*.o bin/*.exe

                if [ "$2" == "only" ]; then
                        echo " "
                        echo "-----------------Clean complete----------------"
                        exit 0; fi
        fi

echo " "
echo "  Begin compliation"

        $COMPILER $CFLAGS_COMPILE $SRC$FILE1\.c

echo "  Relocate files to bin"

        $MOVE_TO_BIN

        $COMPILER $CFLAGS_BUILD $OUT$MAIN $BIN$FILE1\.o $SRC$MAIN\.c

echo "  Compilation complete"
echo " "
echo "-----------------Build complete----------------"
echo " "
echo " "

exit 0
