#!/bin/bash

FILE1='main'
FILE2='types'
FILE3='functions'

COMPILER='gcc'
COMPILER_CLANG='clang'
CFLAGS=' -std=c99 -Wall -O0 -g '

OUTFILE=' -o complex'

$COMPILER $CFLAGS $OUTFILE $FILE2\.c $FILE3\.c $FILE1\.c

if [ "$1" == "run" ]; then
    ./complex $(tput cols) $(tput lines)
else
    if [ "$1" == "valgrind" ]; then
        valgrind -v --leak-check=full --show-leak-kinds=all --track-origins=yes ./complex $(tput cols) $(tput lines)
    fi
fi
