#!/bin/bash

FILE1='main'
FILE2='types'
FILE3='functions'

COMPILER='gcc'
COMPILER_CLANG='clang'
CFLAGS=' -std=c99 -Wall -O0 -g '

OUTFILE=' -o complex'

$COMPILER $CFLAGS $OUTFILE $FILE2\.c $FILE3\.c $FILE1\.c

if [ "$1" == "run" ]; then
    ./complex.exe $(tput cols) $(tput lines)
fi
